# Header
menu:
  Home: /
  Archives: /archives
  About: /about/index.html
rss: /atom.xml
github: https://github.com/denglj/denglj.github.io

# Content
excerpt_link: 阅读全文
fancybox: true

# Sidebar
sidebar: left
widgets:
- category
- archive
- recent_posts
- tag
- tagcloud
- links

# Links
links:
  Hexo: http://hexo.io

# Miscellaneous
google_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:

# 显示版权声明等信息
show_article_info: true
